  
jobs:
- job: PyVSC_Linux
  pool:
   vmImage: 'ubuntu-18.04'

  variables:
  - name: build_num
    value: $(Build.BuildNumber)
  steps:
  - script: |
      python3 --version
      python3 -m pip install --upgrade pip 
      python3 -m pip install wheel twine 
      python3 -m pip install -r requirements_dev.txt 
    displayName: 'Install Python packages'
    
  - script: |
     export PYTHONPATH=$(Build.Repository.LocalPath)/src
     python3 -m pytest ve/unit --cov=./src --cov-report=xml --cov-report=html --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Run Unit Tests'
   
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results'

#  - script: |
#      python scripts/run_pylint.py
#    displayName: 'Run PyLint'

  - task: PublishCodeCoverageResults@1
    inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - script: |
      python3 setup.py bdist_wheel --universal
    displayName: 'Build Wheel'

#  - task: TwineAuthenticate@1
#    condition: eq(variables['Build.SourceBranchName'], 'master')
#    inputs:
#      pythonUploadServiceConnection: pypi-pyvsc
#  - script: |
#      # Only deploy from master
#      if test "$(Build.SourceBranchName)" = "master"; then
#          python -m twine --version
#          echo "Calling twine"
#          python -m twine upload -r py-vsc --config-file $(PYPIRC_PATH) dist/*.whl
#          echo "Calling twine complete"
#      fi
#    displayName: 'Upload to PyPi'


